swagger.url:
  base: localhost:8080
  protocol: http

info:
  app:
    name: drive
    description:
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: info, health

setting:
  whitelist-api-path: ((/webjars/|/swagger-resources|/v2/api-docs|/swagger-ui.html)|(/lib/|/api/|/app/)|(/health|/info|/favicon.ico))
